defaults:
  - _self_
  - base_config
  - policy: foveated_vit_policy
  - task: av_aloha_sim_thread_needle
  - train: short
  - wandb: gaze

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}_${wandb.job_name}

seed: 42
debug: true
device: cuda
resume: false
checkpoint_path: ???