defaults:
  - base_task_config

type: av_aloha_hook_circlev2
dataset_repo_id: Jinyu220/hook_circlev2
dataset_root: /home/jinyu/GitHub/gaze-av-aloha/gym_av_aloha/outputs/Jinyu220/hook_circlev2
dataset_episodes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53] # use all episodes
# gaze_model_kwargs:
#     resize_shape: [224, 224]
override_stats:
  observation.images.left_eye_cam:
    mean: [[[0.485]], [[0.456]], [[0.406]]]
    std: [[[0.229]], [[0.224]], [[0.225]]]
  observation.images.right_eye_cam:
    mean: [[[0.485]], [[0.456]], [[0.406]]]
    std: [[[0.229]], [[0.224]], [[0.225]]]

fps: 11
image_keys:
  - observation.images.left_eye_cam
  # - observation.images.zed_cam_right
state_key: observation.state
action_key: action
state_dim: 14
action_dim: 14