defaults:
  - base_task_config

type: av_aloha_sim
dataset_repo_id: iantc104/av_aloha_sim_thread_needle
dataset_root: ???
dataset_episodes: ??? # use all episodes
override_stats:
  observation.images.zed_cam_left:
    mean: [[[0.485]], [[0.456]], [[0.406]]]
    std: [[[0.229]], [[0.224]], [[0.225]]]

envs:
  thread_needle:
    env_package: "gym_av_aloha"
    env_name: "thread-needle-v1"
    env_kwargs: 
      disable_env_checker: True
      fps: 8.333333333333
      cameras:
        zed_cam_left: [480, 640]
      render_camera: zed_cam_left
      enable_av: True
      max_episode_steps: 100
    eval_n_episodes: 50
    eval_n_envs: 2
    eval_options:
      iid:
        prompt: "thread needle through wall"
      ood_distractors:
        prompt: "thread needle through wall"
        distractors: true
    visualization_steps: 100

fps: 8.333333333333
image_keys:
  - observation.images.zed_cam_left
state_key: observation.state
action_key: action
state_dim: 21
action_dim: 21