defaults:
  - base_task_config

type: av_aloha_sim_hook_package
dataset_repo_id: iantc104/av_aloha_sim_hook_package
dataset_root: ???
dataset_episodes: ??? # use all episodes
override_stats:
  observation.images.zed_cam_left:
    mean: [[[0.485]], [[0.456]], [[0.406]]]
    std: [[[0.229]], [[0.224]], [[0.225]]]
  observation.images.zed_cam_right:
    mean: [[[0.485]], [[0.456]], [[0.406]]]
    std: [[[0.229]], [[0.224]], [[0.225]]]

envs:
  hook_package:
    env_package: "gym_av_aloha"
    env_name: "hook-package-v1"
    env_kwargs: 
      disable_env_checker: True
      fps: 8.333333333333
      cameras:
        zed_cam_left: [480, 640]
        # zed_cam_right: [480, 640]
      render_camera: zed_cam_left
      enable_av: True
      max_episode_steps: 100
    eval_n_episodes: 50
    eval_n_envs: 5
    eval_options:
      iid:
        prompt: "hook package"
      ood_distractors:
        prompt: "hook package"
        distractors: true
      # ood_lighting:
      #   prompt: "hook package"
      #   randomize_light: true
    visualization_steps: 100

fps: 8.333333333333
image_keys:
  - observation.images.zed_cam_left
  # - observation.images.zed_cam_right
state_key: observation.state
action_key: action
state_dim: 21
action_dim: 21