defaults:
  - base_gaze_policy_config

use_gaze: false

vision_encoder: dino
vision_encoder_kwargs:
  crop_shape: [224, 308]

optimizer_lr: 1e-4
optimizer_lr_backbone: 1e-5

image_to_gaze_key:
  observation.images.left_eye_cam: left_eye