defaults:
  - base_task_config

type: av_aloha_sim
dataset_repo_id: iantc104/av_aloha_sim
dataset_root: ???
dataset_episodes: ??? # use all episodes
override_stats:
  observation.images.zed_cam_left:
    mean: [[[0.485]], [[0.456]], [[0.406]]]
    std: [[[0.229]], [[0.224]], [[0.225]]]

envs:
  thread_needle:
    env_package: "gym_av_aloha"
    env_name: "thread-needle-v1"
    env_kwargs: 
      disable_env_checker: True
      fps: 8.333333333333
      cameras:
        zed_cam_left: [480, 640]
      render_camera: zed_cam_left
      enable_av: True
      max_episode_steps: 100
    eval_n_episodes: 1
    eval_n_envs: 1
    eval_options:
      iid:
        prompt: "thread needle through wall"
      ood_distractors:
        prompt: "thread needle through wall"
        distractors: true
    visualization_steps: 100

  hook_package:
    env_package: "gym_av_aloha"
    env_name: "hook-package-v1"
    env_kwargs: 
      disable_env_checker: True
      fps: 8.333333333333
      cameras:
        zed_cam_left: [480, 640]
      render_camera: zed_cam_left
      enable_av: True
      max_episode_steps: 100
    eval_n_episodes: 1
    eval_n_envs: 1
    eval_options:
      iid:
        prompt: "hook package"
      ood_distractors:
        prompt: "hook package"
        distractors: true
    visualization_steps: 100
  
  peg_insertion:
    env_package: "gym_av_aloha"
    env_name: "peg-insertion-v1"
    env_kwargs: 
      disable_env_checker: True
      fps: 8.333333333333
      cameras:
        zed_cam_left: [480, 640]
      render_camera: zed_cam_left
      enable_av: True
      max_episode_steps: 100
    eval_n_episodes: 1
    eval_n_envs: 1
    eval_options:
      iid:
        prompt: "insert peg into socket"
      ood_distractors:
        prompt: "insert peg into socket"
        distractors: true
    visualization_steps: 100

  cube_transfer:
    env_package: "gym_av_aloha"
    env_name: "cube-transfer-v1"
    env_kwargs: 
      disable_env_checker: True
      fps: 8.333333333333
      cameras:
        zed_cam_left: [480, 640]
      render_camera: zed_cam_left
      enable_av: True
      max_episode_steps: 50
    eval_n_episodes: 1
    eval_n_envs: 1
    eval_options:
      iid:
        prompt: "pick red cube"
      ood_distractors:
        prompt: "pick red cube"
        distractors: true
    visualization_steps: 50

  slot_insertion:
    env_package: "gym_av_aloha"
    env_name: "slot-insertion-v1"
    env_kwargs: 
      disable_env_checker: True
      fps: 8.333333333333
      cameras:
        zed_cam_left: [480, 640]
      render_camera: zed_cam_left
      enable_av: True
      max_episode_steps: 75
    eval_n_episodes: 1
    eval_n_envs: 1
    eval_options:
      iid:
        prompt: "insert stick into slot"
      ood_distractors:
        prompt: "insert stick into slot"
        distractors: true
    visualization_steps: 75

  pour_test_tube:
    env_package: "gym_av_aloha"
    env_name: "pour-test-tube-v1"
    env_kwargs: 
      disable_env_checker: True
      fps: 8.333333333333
      cameras:
        zed_cam_left: [480, 640]
      render_camera: zed_cam_left
      enable_av: True
      max_episode_steps: 125
    eval_n_episodes: 1
    eval_n_envs: 1
    eval_options:
      iid:
        prompt: "pour ball into test tube"
      ood_distractors:
        prompt: "pour ball into test tube"
        distractors: true
    visualization_steps: 125

fps: 8.333333333333
image_keys:
  - observation.images.zed_cam_left
state_key: observation.state
action_key: action
state_dim: 21
action_dim: 21