"""ChArUco board definition and detection  (shared by PHASE 5).

The board geometry is CONFIGURATION, never code.  It lives in
``charuco_board.json`` next to this file and every field can be overridden
on the command line.  Nothing here assumes a printed sheet, a monitor size,
or a particular DPI: ``square_length_m`` and ``marker_length_m`` are
physical lengths that YOU measure on the board as it is actually displayed,
and they are the only things that set the scale of every downstream metric
result.

Getting them wrong scales the whole calibration: fx/fy and the distortion
coefficients are unaffected (they are dimensionless in pixels), but every
pose, every translation and eventually every reconstruction inherits the
error linearly.  Measure the displayed square with a ruler, across as many
squares as you can, and divide.

OpenCV API note
    This targets the modern ``cv2.aruco.CharucoDetector`` /
    ``board.matchImagePoints`` / ``cv2.calibrateCamera`` path.  The legacy
    helpers ``interpolateCornersCharuco`` and ``calibrateCameraCharuco``
    were REMOVED in OpenCV 5 (the version in the gym_av312 env), so they
    are not used and no fallback to them exists.

Legacy pattern
    Boards generated by OpenCV < 4.6 start with a white square in the top
    left; newer ones start black.  A mismatch makes detection fail or --
    worse -- succeed with a half-square offset.  ``legacy_pattern`` in the
    config controls it; if you generated the board with THIS module, leave
    it false.
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

import numpy as np

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

try:
    import cv2
except ImportError:
    cv2 = None

BOARD_CONFIG = HERE / "charuco_board.json"

## The predefined dictionaries this module accepts, by the name used in the
## config file.  Resolved lazily so importing without cv2 still works.
DICTIONARIES = (
    "DICT_4X4_50", "DICT_4X4_100", "DICT_4X4_250", "DICT_4X4_1000",
    "DICT_5X5_50", "DICT_5X5_100", "DICT_5X5_250", "DICT_5X5_1000",
    "DICT_6X6_50", "DICT_6X6_100", "DICT_6X6_250", "DICT_6X6_1000",
    "DICT_7X7_50", "DICT_7X7_100", "DICT_7X7_250", "DICT_7X7_1000",
    "DICT_ARUCO_ORIGINAL",
)


def require_cv2() -> None:
    if cv2 is None:
        raise ImportError(
            "opencv is not available in this environment.\n"
            "  The validated env is gym_av312:\n"
            "    conda run -n gym_av312 python calibration/<script>.py")


@dataclass
class BoardSpec:
    """A ChArUco board, in physical units.

    squares_x / squares_y  number of chessboard SQUARES across and down.
                           The detectable interior corners are one fewer in
                           each direction: (squares_x-1) * (squares_y-1).
    square_length_m        physical side of one chessboard square, MEASURED.
    marker_length_m        physical side of the ArUco marker inside a white
                           square, MEASURED.  Must be < square_length_m.
    dictionary             predefined ArUco dictionary name.
    legacy_pattern         see the module docstring.
    """
    squares_x: int = 7
    squares_y: int = 5
    square_length_m: float = 0.030
    marker_length_m: float = 0.022
    dictionary: str = "DICT_5X5_250"
    legacy_pattern: bool = False
    measured: bool = False
    note: str = ""

    # -------------------------------------------------------------- #
    @property
    def n_corners(self) -> int:
        """Interior chessboard corners -- the points calibration uses."""
        return (self.squares_x - 1) * (self.squares_y - 1)

    def validate(self) -> None:
        if self.squares_x < 2 or self.squares_y < 2:
            raise ValueError("squares_x and squares_y must both be >= 2")
        if self.marker_length_m >= self.square_length_m:
            raise ValueError(
                f"marker_length_m ({self.marker_length_m}) must be smaller "
                f"than square_length_m ({self.square_length_m})")
        if self.square_length_m <= 0:
            raise ValueError("square_length_m must be positive")
        if self.dictionary not in DICTIONARIES:
            raise ValueError(f"dictionary must be one of {DICTIONARIES}")
        need = (self.squares_x * self.squares_y) // 2
        avail = int(self.dictionary.rsplit("_", 1)[-1]) \
            if self.dictionary != "DICT_ARUCO_ORIGINAL" else 1024
        if need > avail:
            raise ValueError(
                f"board needs {need} markers but {self.dictionary} only has "
                f"{avail}")

    # -------------------------------------------------------------- #
    def cv_dictionary(self):
        require_cv2()
        return cv2.aruco.getPredefinedDictionary(
            getattr(cv2.aruco, self.dictionary))

    def cv_board(self):
        require_cv2()
        self.validate()
        board = cv2.aruco.CharucoBoard(
            (self.squares_x, self.squares_y),
            float(self.square_length_m),
            float(self.marker_length_m),
            self.cv_dictionary())
        board.setLegacyPattern(bool(self.legacy_pattern))
        return board

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d["interior_corners"] = self.n_corners
        d["board_size_m"] = [self.squares_x * self.square_length_m,
                             self.squares_y * self.square_length_m]
        return d

    def describe(self) -> str:
        w, h = (self.squares_x * self.square_length_m,
                self.squares_y * self.square_length_m)
        return (
            f"{self.squares_x}x{self.squares_y} squares, "
            f"square {self.square_length_m * 1e3:.3f} mm, "
            f"marker {self.marker_length_m * 1e3:.3f} mm, "
            f"{self.dictionary}, legacy={self.legacy_pattern}\n"
            f"      {self.n_corners} interior corners; "
            f"full board {w * 1e3:.1f} x {h * 1e3:.1f} mm"
            + ("" if self.measured else
               "\n      *** square/marker lengths are NOT marked as measured "
               "-- every metric\n      result downstream is scaled by them "
               "(see charuco_board.json) ***"))


## ------------------------------------------------------------------ ##
## Config file
## ------------------------------------------------------------------ ##

def load_spec(path: Path = BOARD_CONFIG, **overrides) -> BoardSpec:
    """Read charuco_board.json, then apply any non-None CLI overrides."""
    from common import load_json

    data: Dict[str, Any] = {}
    p = Path(path)
    if p.exists():
        raw = load_json(p)
        data = {k: v for k, v in raw.items() if not k.startswith("_")}
    fields = set(BoardSpec.__dataclass_fields__)
    kwargs = {k: v for k, v in data.items() if k in fields}
    kwargs.update({k: v for k, v in overrides.items()
                   if k in fields and v is not None})
    spec = BoardSpec(**kwargs)
    spec.validate()
    return spec


def add_board_args(ap) -> None:
    """Attach the board overrides to an argparse parser."""
    g = ap.add_argument_group("board geometry (overrides charuco_board.json)")
    g.add_argument("--board-config", default=str(BOARD_CONFIG))
    g.add_argument("--squares-x", type=int, default=None)
    g.add_argument("--squares-y", type=int, default=None)
    g.add_argument("--square-length", type=float, default=None,
                   dest="square_length_m",
                   help="physical square side in METRES (measure it)")
    g.add_argument("--marker-length", type=float, default=None,
                   dest="marker_length_m",
                   help="physical marker side in METRES (measure it)")
    g.add_argument("--dictionary", default=None, choices=DICTIONARIES)
    g.add_argument("--legacy-pattern", dest="legacy_pattern",
                   action="store_true", default=None)


def spec_from_args(args) -> BoardSpec:
    return load_spec(
        Path(args.board_config),
        squares_x=getattr(args, "squares_x", None),
        squares_y=getattr(args, "squares_y", None),
        square_length_m=getattr(args, "square_length_m", None),
        marker_length_m=getattr(args, "marker_length_m", None),
        dictionary=getattr(args, "dictionary", None),
        legacy_pattern=getattr(args, "legacy_pattern", None),
    )


## ------------------------------------------------------------------ ##
## Detection
## ------------------------------------------------------------------ ##

@dataclass
class Detection:
    ok: bool
    n_corners: int
    charuco_corners: Optional[np.ndarray] = None   # (N, 2) float32
    charuco_ids: Optional[np.ndarray] = None       # (N,)   int
    obj_points: Optional[np.ndarray] = None        # (N, 3) float32, board frame
    img_points: Optional[np.ndarray] = None        # (N, 2) float32, pixels
    n_markers: int = 0
    reason: str = ""


def make_detector(spec: BoardSpec):
    require_cv2()
    board = spec.cv_board()
    detector = cv2.aruco.CharucoDetector(board)
    ## Corner refinement lifts corner localisation from integer-ish to
    ## sub-pixel, which is where calibration accuracy actually comes from.
    params = detector.getDetectorParameters()
    params.cornerRefinementMethod = cv2.aruco.CORNER_REFINE_SUBPIX
    detector.setDetectorParameters(params)
    return detector, board


def detect(image: np.ndarray, detector, board,
           min_corners: int = 6) -> Detection:
    """Find the board in one image and build calibration correspondences.

    `image` may be grayscale, BGR or RGB; detection runs on gray."""
    require_cv2()
    gray = _to_gray(image)
    charuco_corners, charuco_ids, marker_corners, marker_ids = \
        detector.detectBoard(gray)

    n_markers = 0 if marker_ids is None else int(len(marker_ids))
    if charuco_ids is None or len(charuco_ids) < min_corners:
        n = 0 if charuco_ids is None else int(len(charuco_ids))
        return Detection(False, n, n_markers=n_markers,
                         reason=f"only {n} charuco corners "
                                f"(need >= {min_corners})")

    obj_points, img_points = board.matchImagePoints(charuco_corners,
                                                    charuco_ids)
    if obj_points is None or len(obj_points) < min_corners:
        return Detection(False, int(len(charuco_ids)), n_markers=n_markers,
                         reason="matchImagePoints returned too few points")

    ## A view whose corners are collinear carries no information about the
    ## board plane and makes calibrateCamera singular.
    try:
        if board.checkCharucoCornersCollinear(charuco_ids):
            return Detection(False, int(len(charuco_ids)),
                             n_markers=n_markers,
                             reason="detected corners are collinear")
    except Exception:
        pass

    return Detection(
        True, int(len(charuco_ids)),
        charuco_corners=np.asarray(charuco_corners, dtype=np.float32).reshape(-1, 2),
        charuco_ids=np.asarray(charuco_ids).reshape(-1),
        obj_points=np.asarray(obj_points, dtype=np.float32).reshape(-1, 3),
        img_points=np.asarray(img_points, dtype=np.float32).reshape(-1, 2),
        n_markers=n_markers)


def _to_gray(image: np.ndarray) -> np.ndarray:
    if image.ndim == 2:
        return image
    if image.shape[2] == 3:
        return cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    return cv2.cvtColor(image, cv2.COLOR_BGRA2GRAY)


def annotate(image: np.ndarray, det: Detection) -> np.ndarray:
    """Draw the detected corners for visual checking."""
    require_cv2()
    out = image.copy()
    if out.ndim == 2:
        out = cv2.cvtColor(out, cv2.COLOR_GRAY2BGR)
    if det.ok and det.charuco_corners is not None:
        cv2.aruco.drawDetectedCornersCharuco(
            out, det.charuco_corners.reshape(-1, 1, 2),
            det.charuco_ids.reshape(-1, 1).astype(np.int32), (0, 255, 0))
    txt = (f"{det.n_corners} corners / {det.n_markers} markers"
           if det.ok else f"REJECTED: {det.reason}")
    cv2.putText(out, txt, (8, 22), cv2.FONT_HERSHEY_SIMPLEX, 0.6,
                (0, 255, 0) if det.ok else (0, 0, 255), 2)
    return out


def generate_image(spec: BoardSpec, pixels_per_metre: float = 4000.0,
                   margin_px: int = 20,
                   size_px: Optional[Tuple[int, int]] = None) -> np.ndarray:
    """Render the board for printing or for display on a monitor.

    `pixels_per_metre` only sets the rendering resolution -- it does NOT
    determine the physical size, which depends on how the image is printed
    or displayed.  Measure the result and put the measurement in
    charuco_board.json.

    `size_px` overrides the computed output size.  It exists because
    OpenCV fits the board inside `size_px` MINUS the margins while keeping
    the squares square, so a size derived from pixels_per_metre alone
    comes out a few percent smaller per square than asked -- fine for
    printing, wrong for "render exactly N pixels per square"."""
    require_cv2()
    board = spec.cv_board()
    if size_px is None:
        w = int(round(spec.squares_x * spec.square_length_m * pixels_per_metre))
        h = int(round(spec.squares_y * spec.square_length_m * pixels_per_metre))
    else:
        w, h = (int(size_px[0]), int(size_px[1]))
    return board.generateImage((w, h), marginSize=margin_px)
