defaults:
  - base_foveated_policy_config

type: foveated_policy

input_shape: [480, 640] 
crop_shape: [432, 576]
resize_shape: [224, 224] 

backbone: dino
freeze_n_layers: 6
use_gaze: false
use_action_history: false

# Gaze
image_to_gaze_key:
  observation.images.zed_cam_left: left_eye