defaults:
  - base_gaze_policy_config

use_gaze: true

vision_encoder: dino
vision_encoder_kwargs:
  crop_shape: [224, 308]

optimizer_lr: 1e-4
optimizer_lr_backbone: 1e-4

image_to_gaze_key:
  observation.images.zed_cam_left: left_eye