defaults:
  - base_gaze_policy_config

use_gaze: true
use_gaze_as_action: true

vision_encoder: foveated_vit
vision_encoder_kwargs:
  repo_id: ''
  token_size: 16
  strides: [1, 2, 6]
  grid_sizes: [2, 3, 3]
  height: 288
  width: 288

optimizer_lr: 1e-4
optimizer_lr_backbone: 1e-4

image_to_gaze_key:
  observation.images.zed_cam_left: left_eye