defaults:
  - base_gaze_policy_config

use_gaze: false

vision_encoder: vit
vision_encoder_kwargs:
  repo_id: ''
  crop_shape: [216, 288]
  token_size: 64
  height: 256
  width: 320

optimizer_lr: 1e-4
optimizer_lr_backbone: 1e-4

image_to_gaze_key:
  observation.images.zed_cam_left: left_eye