defaults:
  - base_gaze_policy_config

type: gaze_policy

input_shape: [240, 320]
periph_shape: [224, 224]
periph_crop_scale: 0.9

freeze_n_layers: 6
use_gaze: false

# Gaze
image_to_gaze_key:
  observation.images.zed_cam_left: left_eye