defaults:
  - base_gaze_policy_config

type: gaze_policy

n_obs_steps: 1
obs_step_size: 1

image_to_gaze_key:
  observation.images.zed_cam_left: left_eye
input_shape: [240, 320]

patch_size: 16
vit_input_shape: [288, 288]
use_gaze: false
crop_scale: 1.0

optimizer_lr: 1e-4
optimizer_lr_backbone: 1e-4