defaults:
  - base_foveated_policy_config

type: foveated_policy

input_shape: [480, 640] 
crop_shape: [432, 576]
resize_shape: [1280, 1280]

backbone: stt
freeze_n_layers: 0
gaze_noise: 0.02
use_gaze: true
use_action_history: false

# Gaze
image_to_gaze_key:
  observation.images.zed_cam_left: left_eye