defaults:
  - base_gaze_policy_config

use_gaze: false

vision_encoder: vit
vision_encoder_kwargs:
  crop_shape: [216, 288]
  token_size: 16
  height: 288
  width: 288

optimizer_lr: 1e-4
optimizer_lr_backbone: 1e-4

image_to_gaze_key:
  observation.images.zed_cam_left: left_eye